export const types = {
   
   
    FETCH_GRID_DATA: "FETCH_GRID_DATA",
    SET_GRID_DATA: "SET_GRID_DATA",
  
    SAVE_GRID_SORT_MODEL: "SAVE_GRID_SORT_MODEL",
    SAVE_GRID_FILTER_MODEL: "SAVE_GRID_FILTER_MODEL",
  
    SAVE_GRID_COLUMN_STATE: "SAVE_GRID_COLUMN_STATE",
    SAVE_GRID_COLUMN_GROUP_STATE: "SAVE_GRID_COLUMN_GROUP_STATE",
    SAVE_GRID_PIVOT_MODE_STATE: "SAVE_GRID_PIVOT_MODE_STATE",
  
    SAVE_STORE_STATE_TO_LOCAL_STORAGE: "SAVE_STORE_STATE_TO_LOCAL_STORAGE",
    RESTORE_STORE_STATE_TO_LOCAL_STORAGE: "RESTORE_STORE_STATE_TO_LOCAL_STORAGE",
  
    SET_GRID_FETCH_AGAIN_TO_FALSE: "SET_GRID_FETCH_AGAIN_TO_FALSE",
    //SET_ROW_SELECTION_SYNC_STATUS: "SET_ROW_SELECTION_SYNC_STATUS",
  };
  