
export const types = {
SET_GRID_DATA: "SET_GRID_DATA",
  
SAVE_GRID_SORT_MODEL: "SAVE_GRID_SORT_MODEL",
SAVE_GRID_FILTER_MODEL: "SAVE_GRID_FILTER_MODEL",

SAVE_GRID_COLUMN_STATE: "SAVE_GRID_COLUMN_STATE",
SAVE_GRID_COLUMN_GROUP_STATE: "SAVE_GRID_COLUMN_GROUP_STATE",
SAVE_GRID_PIVOT_MODE_STATE: "SAVE_GRID_PIVOT_MODE_STATE",
}